package cz.wrent.advent.day6

import org.junit.jupiter.api.Assertions.*

class PatrolGuardKtTest {

    @org.junit.jupiter.api.Test
    fun testPartOne() {
        val input = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."""

        assertEquals(41, findVisitedPlaces(input))
    }

    @org.junit.jupiter.api.Test
    fun testPartTwo() {
        val input = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."""

        assertEquals(6, findObstacleOptions(input))
    }
}
