package cz.wrent.advent.day8

import org.junit.jupiter.api.Assertions.*

class AntenaAntinodesKtTest {

    @org.junit.jupiter.api.Test
    fun testPartOne() {
        val input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".trimIndent()

        assertEquals(14, findAntinodes(input))
    }

    @org.junit.jupiter.api.Test
    fun testPartTwo() {
        val input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".trimIndent()

        assertEquals(34, findAntinodesWithHarmonicResonant(input))
    }
}
